name: test-prom

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
    expose: 
      - 9090
  testobs:
    image: test-obs
    container_name: test-obs-01
    networks:
      - localprom
    ports:
      - "9400:9400"
    expose: 
      - 9400
networks:
  localprom:
    driver: bridge
